-- Expand role_code_enum with full workflow roles.
ALTER TYPE "role_code_enum" ADD VALUE IF NOT EXISTS 'EMPLOYEE';
ALTER TYPE "role_code_enum" ADD VALUE IF NOT EXISTS 'UNIT_COORDINATOR';
ALTER TYPE "role_code_enum" ADD VALUE IF NOT EXISTS 'SELECTION_COMMITTEE';
ALTER TYPE "role_code_enum" ADD VALUE IF NOT EXISTS 'IMPLEMENTER';
ALTER TYPE "role_code_enum" ADD VALUE IF NOT EXISTS 'BUSINESS_EXCELLENCE';
ALTER TYPE "role_code_enum" ADD VALUE IF NOT EXISTS 'BUSINESS_EXCELLENCE_HEAD';
ALTER TYPE "role_code_enum" ADD VALUE IF NOT EXISTS 'HOD_FINANCE';
ALTER TYPE "role_code_enum" ADD VALUE IF NOT EXISTS 'HOD_HR';
ALTER TYPE "role_code_enum" ADD VALUE IF NOT EXISTS 'HOD_QUALITY';
ALTER TYPE "role_code_enum" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
